#! /bin/bash

# Contents of the directory declared in dir_src will be the source used for the backup
dir_src="/root"

# The directory declared in dir_dest will be used to store the backups
# If the directory doesn't exist, minibak will attempt to create it
dir_dest="/root/root.minibak"

# placeholder
bool_schedulerEnabled=0

# Logs from execution of the script will be saved in this directory.
dir_log="/var/log"
